### ISSUE TITLE
change source url

### ISSUE THREAD

**Issue by damonkman** [shadowmoose/poe-aura-calc#1]
change 'https://raw.githubusercontent.com/brather1ng/RePoE/master/data/gem_tooltips.min.json'
to 'https://raw.githubusercontent.com/brather1ng/RePoE/master/RePoE/data/gem_tooltips.min.json' in data.js 

Currently doesn't work unless you make that change

**Comment by shadowmoose** [comment]
Fixed. 
Thanks for pointing the bug out, and also hunting down the new URL.

Make sure to refresh with a clear cache, to avoid github storing the old js script.
