### ISSUE TITLE
Nercrian phys damage reduction and defiance banner prasing fix 

### ISSUE THREAD

**Issue by nzlrhyz** [shadowmoose/poe-aura-calc#12]
Line 224: 

'#% Physical Damage Reduction': {scaling: 1},

Change to 

'#% additional Physical Damage Reduction': {scaling: 1},

That way it'll parse in POB correctly 

Also Defiance banner

 Buff grants #% increased Evasion Rating and Armour
 
 needs to be 
 "#% increased Evasion Rating and Armour"

**Comment by shadowmoose** [comment]
Thanks for the issue report. Fixed.
