### ISSUE TITLE
RePoE update massively changed structure

### ISSUE THREAD

**Issue by damonkman** [shadowmoose/poe-aura-calc#5]
RePoE's gem data, https://raw.githubusercontent.com/brather1ng/RePoE/master/RePoE/data/gems.min.json
is structured completely differently and will require quite a bit of work to update to new format. 
Can use legacy source 'https://raw.githubusercontent.com/brather1ng/RePoE/a40af396ecd2b9391a3a14aead7987298c62b799/RePoE/data/gem_tooltips.json'
until update to allow continued function with old values (mainly Vitality changed + alt quality potential)

**Comment by shadowmoose** [comment]
This app has been updated to work with the new data structure.
