### ISSUE TITLE
https://aura.poe.farm/ appears to be not working correctly, missing most of the auras

### ISSUE THREAD

**Issue by toddf2p** [shadowmoose/poe-aura-calc#6]
https://aura.poe.farm/ tried multiple browsers
![image](https://user-images.githubusercontent.com/4283977/106370454-02595400-630f-11eb-9935-0b05ff5b69d2.png)

**Comment by shadowmoose** [comment]
Good catch - it looks like the data we're using was updated to not include level data for some skills. I've fixed this problem, and updated the Guardian class while I was at it.
