### ISSUE TITLE
Physical Damage Reduction state not parsed by POB

### ISSUE THREAD

**Issue by melink14** [shadowmoose/poe-aura-calc#7]
I believe it should be 'Additional Physical Damage Reduction' which parses correctly and seems to have the same effect.

**Comment by shadowmoose** [comment]
Strange, this works fine in my PoB. Maybe that's because I'm using the community fork though. Either way, I've reworded it now.

**Comment by melink14** [comment]
I'm also using the community fork so it's a mystery! Thanks a lot!
