### ISSUE TITLE
Regeneration stats not correct due to early rounding

### ISSUE THREAD

**Issue by melink14** [shadowmoose/poe-aura-calc#8]
I noticed that my clarity buffs were a few points off and did some digging.

Regeneration rates are stored per minute which means they can have non-integer per second values.

Right now poe-aura-calc converts to an integer per second value first and then applies aura modifiers which means the final value ends up being a bit smaller than you see in game or in POB.

I think the easiest fix would be to not convert to per second until after the buffs; and when you do, don't use `floor` since the in game value will not be floored. For visual clarity, it'd probably be fine truncated to 1 or 2 decimal places (POB uses 2).

https://github.com/shadowmoose/poe-aura-calc/blob/861d785ae37a3b46686ed694d6c3d61e94bbb690/docs/script/data.js#L87-L88

**Comment by shadowmoose** [comment]
I believe I have fixed this now, nice catch.
